# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Linting and Formatting"

on:
  pull_request:
    paths:
      - "**.py"
      - "pyproject.toml"

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Run Ruff Linter
        id: ruff-lint
        uses: astral-sh/ruff-action@v3
        continue-on-error: true

      - name: Run Ruff Formatter
        id: ruff-format
        uses: astral-sh/ruff-action@v3
        continue-on-error: true
        with:
          args: "format --check"

      - name: Run Pyright (Pylance equivalent)
        id: pyright
        continue-on-error: true
        uses: jakebailey/pyright-action@v2
        with:
          pylance-version: latest-release

      - name: Check Linter Statuses
        if: always() # This ensures the step runs even if previous steps failed
        run: |
          if [[ "${{ steps.ruff-lint.outcome }}" == "failure" || \
                "${{ steps.ruff-format.outcome }}" == "failure" ]]; then
            echo "One or more linting/checking steps failed."
            exit 1
          fi
